### ISSUE TITLE
sipaddr used before assignment in scamper module

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#10]
In pathspider.scamper.scamper in the function __input_trace(self,spec):

srcaddr    = sipaddr#spec.get_parameter_value("scamper.trace.srcaddr")

This appeared in 5df8764b by @gubser. Should this be using the commented out value instead?

**Comment by gubser** [comment]
I've just copied that code over from the scamper/tracebox repo. (sorry for that ;-) cherry picking across repositories ugh..)

https://github.com/fp7mplane/components/tree/master/scamper 

But this function is never used from pathspider anyway. I only use the tracebox stuff.

**Comment by irl** [comment]
Ah ok, @gubser can you go through and strip the code that's not needed? If that sounds like a good idea, we can file a separate issue for that and close this one.

**Comment by gubser** [comment]
Imho, scamper/tracebox component doesn't belong here anyway. The entire folder can be deleted. When deploying on a server, the scamper component needs to be added separately.
Ideally using pypi or git clone etc..

@britram what do you say?

**Comment by irl** [comment]
I would prefer to have the scamper component as an external dependency, otherwise we end up maintaining what is essentially a fork of scamper within pathspider, which is just duplicated effort.

**Comment by britram** [comment]
Yep, this should live in a separate repo under the mami-project org, and be installed as a separate package. Question is: should it be part of the (C) scamper+tracebox source repo, or a separate repo just for the component? @ekorian: opinions?


Sent from my iPhone

**Comment by irl** [comment]
This was fixed by the removal of the scamper module.
