### ISSUE TITLE
plugins should also have a version

### ISSUE THREAD

**Issue by pietdevaere** [mami-project/pathspider#101]
and this version should be included in the PTO-upload metadata

**Comment by irl** [comment]
For plugins that are in core PATHspider, this should be the version of PATHspider. External plugins can also have versions, and I'll do docfixes for exposing these. I think moving plugins out of the PATHspider distribution into their own packages should be a goal for the next release of PATHspider so they are maintained in separate PyPI packages.

**Comment by britram** [comment]
This version should also refer to the version of the test specification.

**Comment by irl** [comment]
@britram What do we want to do with these versions?

**Comment by britram** [comment]
The latter is sufficient, I think. With PTO we're moving to a "per-file/observation-set" model for metadata.

**Comment by irl** [comment]
Ok, this also works for the OONI report format.
