### ISSUE TITLE
Namespaces for PATHspider records

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#105]
#77, #78 and #95 all require that we've got a single dict that we pass around and add more data to as records pass through the PATHspider pipeline.

We need to consider namespaces for the record field names. [hellfire](https://github.com/irl/hellfire/), a future replacement for dnsresolv, currently passes through any metadata untouched (e.g. Alexa rank, Citizen Lab source/notes/category ...) but I think we need to be more careful.

The can be unknown fields at:

 * The input to the resolver
 * The output of the resolver (the format is described and people may choose to generate their own input lists using their own tool)
 * The output of plugins

**Comment by britram** [comment]
I think this is pretty straightforward:

- pathspider core reads in fdjson into maps, and it's the creator's responsibility to make sure that a minimum set of keys in each object have reasonable values
- pathspider reserves keys beginning with "_" for internal use.
- plugins reserve "_<pluginname>_" as a prefix for their own internal use

**Comment by britram** [comment]
Do this as part of #95

**Comment by irl** [comment]
Fixed in #119
