### ISSUE TITLE
Generalize framework to n-configuration testing

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#109]
Instead of config zero and config one, PathSpider should support an arbitrary number of configurations, determined by the plugin.

**Comment by britram** [comment]
Use a new spider class for this; existing plugins can then stay with the two-configuration world.

**Comment by irl** [comment]
I feel like, for the desync case, this is waaaaay easier than we think it is. @adventureloop has a tool that could potentially be remodelled as a pathspider plugin using an n-configuration desync spider. If that works nicely, we can target 2.0 for the desync version, 2.1 for the synced version.

**Comment by britram** [comment]
It's actually not all that difficult in the sync case, even -- it's simply (probably) excruciatingly slow, and more susceptible to transient effects.

**Comment by irl** [comment]
This is probably done.
