### ISSUE TITLE
Re-merge `piet-dev` on to master, this time with testing

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#110]

**Comment by irl** [comment]
All the stuff relating to dnsresolv is now merged. For the PTO bits, I'm not going to cherry-pick those but will instead just copy bits in to a new commit where they fit. I'm not convinced by the http_get code, it seems to have issues that can be avoided entirely by using a library function.

I've merged 551 lines of diff, 1464 lines remain.

**Comment by irl** [comment]
I'm going to mark this as closed, as the http_get is handled by #112, PTO by #116 and ECN combining by #115.
