### ISSUE TITLE
Add helpers.py

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#112]
Lots of plugins have to do similar things - open a socket, connect to Tor, make an HTTP request, etc. We should design this intentionally, factor out potential helpers from existing plugins, and make these available as part of the API Pathspider provides plugin authors.

**Comment by irl** [comment]
#73 will be good for binding on the right interface, we should wait for that

**Comment by irl** [comment]
We've started on this, specific things should have specific issues.
