### ISSUE TITLE
Add chains.py

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#113]
We can probably reuse observer chain functions across plugins (as with helpers). Design this intentionally too.

**Comment by britram** [comment]
This is in progress in task/113: pulled out the functions from observer.icmp, observer.tcp, and the plugins (except tls) into a new observer.chains module.

Things that should happen now:

1. generalize TCP options parsing
2. normalize function names: suggest `chain_initial_`_name_ and `chain_`_layer_`_`_name_
3. fix #91 in new `chain_tcp_ecn()`
4. hook up the plugins to the new chain functions

**Comment by irl** [comment]
I would look at #119 before following on with this. Didn't see this as you didn't have a WIP pull request.

**Comment by irl** [comment]
I'm also not convinced by a single chains.py. We're going to be adding quite a few plugins soon, even if we just add basic chains for each of the popular transport protocols, that's a lot of chains. Why the objection to `pathspider.observer.<protocol>`?

**Comment by britram** [comment]
no objection, that's just what I thought we'd agreed on. Hadn't done a WIP PR because I wasn't yet convinced we actually needed to do this. Having looked at all the chain functions together in one place, I don't think we need to do that. 

At most, I think the naming changes should be made.

**Comment by irl** [comment]
I was considering having a class, which contains a dict of chains that the Observer appends functions of the class from.

```
class TCPChains:
    self.chains = {'new_flow': self.chain_tcp_new_flow, 'tcp': self.chain_tcp_tcp}
    def tcp_new_flow(blah):
    etc.
```

The observer can then have an argument that accepts these functions, which makes working out which ones go together a lot easier.
