### ISSUE TITLE
Output format should expand to contain well-formed paths

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#114]

**Comment by britram** [comment]
#99 and #111 will generate better path information. We should encode this as PTO-compatible paths.

**Comment by irl** [comment]
* Internet  hosts: ["``{vantage point ip}``", "``{asn of public ip}``", "``{asn of target}``", "``{target ip}"``]
* Hosts behind NAT: ["``mac:{first hop}``", "``{public ip}``", "``{asn of public ip}``", "``{asn of target}``", "``{target ip}"``]
* Tor Exits: ["``tor:{fingerprint}``", "``{exit relay OR address}``", "``{asn of public ip}``", "``{asn of target}``", "``{target ip}"``]

**Comment by irl** [comment]
@britram Did you decide how to represent mac addresses and tor fingerprints in the PTO?

**Comment by britram** [comment]
All of these are basically pseudonyms. I'll have to write something about pseudonyms and the contract around them in pto3-go/API.md, but for now, "any hex string longer than 8 chars" will be a pseudonym.

**Comment by britram** [comment]
MAC: 12+ character  hash of the mac address. TOR identifier: 40 characters. PTO won't care what they mean, just that they're distinct. Note ffffffff != 0ffffffff
