### ISSUE TITLE
ECN IP condition logic incorrect

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#115]
(1) Reverting piet-dev reverted fixes to the ECN condition logic in `ecn.ECN.combine_flows(); what's in master right now is simply broken and should not be used.

(2) In any case, the logic in piet-dev is also flawed.

Here are the conditions we want:

`ecn.connectivity.*` these are okay ("transient" is poorly named but we can keep it for historical reasons)

`ecn.negotiated` and `ecn.not_negotiated` should be renamed `ecn.negotiation.succeeded` and `ecn.negotiation.failed`, to allow an `ecn.negotiated.*` condition in the PTO to work properly.

IP marking conditions should be replaced with the following conditions: `ecn.ipmark.(ect0,ect1,ce).(seen,not_seen)`.

**Comment by irl** [comment]
Once #119 is merged, the combiner for ECN will be disabled and so this will not be a bug on master. The combiner needs to be rewritten slightly to take account for retrieving the job record, so this should be done at the same time.
