### ISSUE TITLE
stringify ip addresses everywhere

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#14]
mPlane results use the `ipaddress` module to represent IP addresses. Pandas and everything after it on the client side should use IP addresses as strings, since strings are waaaaaaaay faster than objects in NumPy.

Now we're stringifying in about half the places that might matter. This is bad, since ipaddress("1.0.0.0") != "1.0.0.0".

Fix this by stringifying addresses *as soon as* they come out of the mPlane results from the components.

**Comment by gubser** [comment]
fixed in 14617e6f0290089abd919947114807e63cffc7e4 and fae06a9b17895684957c5211026040ef96c4c4aa

I think I've got'em all.
