### ISSUE TITLE
TFO plugin cannot merge flow records

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#151]
Due to curl/curl#1332 it is not currently possible for the TFO plugin to merge flow records with spider records. If this is not resolved in curl, we will have to revert to using separate logic for the TFO plugin.

**Comment by irl** [comment]
The plugin is not completely useless, curl still lets us know if the connection succeeded or not, it's just the Observer chain results are lost as they don't get matched back up.

**Comment by irl** [comment]
The dnstcp connection works fine though, so maybe that could be the default mode for now...

**Comment by irl** [comment]
Submitted pull request curl/curl#1847.

**Comment by britram** [comment]
Release 2.0 with TFO disabled.

**Comment by irl** [comment]
The plugin has reverted to using manual socket handling for now.
