### ISSUE TITLE
Observer class hangs when passed an interface that isn't up

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#16]
When initialising an Observer instance with a libtrace URI that is an interface that is down, everything just hangs and doesn't even respond to Ctrl+C.

**Comment by irl** [comment]
@britram I have no ideas for this. Do you have any ideas?

**Comment by britram** [comment]
I think the answer here is "don't do that, then". Probably involves rooting around in python-libtrace. Let's come back around and dig into this one later.

**Comment by irl** [comment]
Changes the milestone on this one then, we can deal with this later.

**Comment by britram** [comment]
We'll need to have a look at python-libtrace anyway for accelerating TFO. I'm talking to Nevil next week about getting his code into github, and what would be necessary to add features to it.

**Comment by irl** [comment]
In order to fully support multihoming I'll be using pyroute2 (interface to netlink) which means we can add a test to check to see the interface is up before starting.

**Comment by irl** [comment]
netlink code is now merged, and this is no longer affecting pathspider, though is still a problem in python-libtrace.
