### ISSUE TITLE
Document and write tests for combiners

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#160]
Combiners should be documented in their docstrings, with that information included in the Sphinx docs. Unit tests should be written for the combiners with pre-constructed flow records as inputs (as if they were output by the merger).

* [x] ECN
* [x] DSCP
* [x] H2
* [x] UDP Zero Checksum
* [x] Evil Bit (@ana-cc)
* [x] MSS

**Comment by irl** [comment]
The combiners and conditions are documented on master, but not via docstrings and no tests are currently present.

**Comment by irl** [comment]
Removed UDP options from the list as this plugin is really not that well defined yet.

**Comment by ana-cc** [comment]
Sent patch for EvilBit, ECN and DSCP combiner tests.
