### ISSUE TITLE
Allow all spiders to skip or discard connections/jobs

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#162]
Currently only DesyncSpider can do this.

**Comment by irl** [comment]
The relevant code in DesyncSpider is here:

https://github.com/mami-project/pathspider/blob/master/pathspider/desync.py#L7 and
https://github.com/mami-project/pathspider/blob/master/pathspider/desync.py#L100-L115

This should be added to SyncSpider.

**Comment by ana-cc** [comment]
Note to self: Abort jobs which are going to be discarded anyway

**Comment by irl** [comment]
Fixed by #182
