### ISSUE TITLE
Add mPlane support to new plugin-based harness

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#18]
In order to speed up development to a point where we can run new tests, mPlane support became a casualty. We should add it back.

**Comment by britram** [comment]
Given that the websockets component daemon uses `asyncio`, and pathspider itself is an ~~unholy~~ delicately balanced mix of `threading` and `multiprocessing`, I suspect the we should use the mPlane proxy model here: the mplane component should publish capabilities, convert specifications to command line invocation, and `Popen` PathSpider in "give me mplane-formatted results" mode,  then read the output and frame it appropriately.

This should probably encompass #9, as well.
