### ISSUE TITLE
Standalone harness should exit when all jobs processed

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#21]
Currently no way of detecting this easily

**Comment by britram** [comment]
This work is happening for the multiprocess observer in `mpo-all-results`. Added shutdown sentinel cascade all the way from the workers to the merger, but `stop()` still never returns. Debugging continues on Tuesday.

**Comment by britram** [comment]
Fixed by 58d46a5ede8dd2ca986328668a758f1048b5d122 (in `multiprocessing-observer`), needs merge to master.

**Comment by irl** [comment]
This is merged to master now.
