### ISSUE TITLE
installing python3-pyroute2

### ISSUE THREAD

**Issue by mirjak** [mami-project/pathspider#233]
I just installed pathspider and I had to manually install python3-pyroute2 as pip install pyroute2 did install it only for python2.7

**Comment by irl** [comment]
On Debian systems you will need to run "pip3 install pyroute2". In practice all testing happens against the Debian package anyway and so installing from pip might not do what you want.

To install all the dependencies from pip:

```
pip3 -r requirements.txt
```

**Comment by britram** [comment]
FWIW, this does not appear to work.

`pip3 install 'cat requirements.txt'` does (with backticks as appropriate), at least on deb9.

**Comment by irl** [comment]
The command is `pip3 install -r requirements.txt`. This is updated in the documentation at:

https://pathspider.readthedocs.io/en/latest/installation.html

The virtualenv method is probably the preferred method when not using the Debian package and we will probably drop the non-virtualenv method before the next release.

#260 needs to still be fixed, which I discovered today using the latest Ubuntu release.
