### ISSUE TITLE
Merger should detect missing flows

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#29]
On overloaded machines, the observer might miss packets. The merger should use the records from the workers as ground truth, and flag such records without matching flows so that the merger (and later analysis) can estimate how many packets were missed.

**Comment by britram** [comment]
There's a fix for this in `Spider.merger()` in the `clean-shutdown` branch, but it's commented out until the plugins can handle null flows.

@gubser, @irl, @agermann93 : The right thing to do here is to rewrite each plugin's `merge()` to handle the case where the flow doesn't exist, after we've merged all the observer threads back to master.

**Comment by britram** [comment]
@gubser: this is done in ecnspider3.py for testing purposes in the `mpo-all-results` branch

**Comment by britram** [comment]
This is no longer commented out in `multiprocessing-observer`, which means that tfospider will also choke on missing flows. Have added @agermann93 to fix this :)

**Comment by irl** [comment]
@agermann93 have you looked at this?

**Comment by irl** [comment]
The code has an if NO_FLOW in it, marking closed, assuming it works.
