### ISSUE TITLE
add TCP Fast Open testing

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#3]

**Comment by irl** [comment]
In the branch standalone-observer-tfo and will be merged once the plugin architecture is in place.

**Comment by irl** [comment]
Merged to standalone-observer

**Comment by britram** [comment]
agermann93 is finshed with his thesis; the code here could use some additional tests and the performance is not great (due to the fact that libtrace as-is doesn't parse TCP options for you). but it works for now. so closing this bug.
