### ISSUE TITLE
ECNSpider should generate observations, not flow data

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#31]
ECNSpider currently generates one row of output per flow; instead, it should generate one row of output per path, with an additional key "condition". Conditions should include:

- ~~ECN not negotiated but ECT/CE mark observed~~
- ~~ECN negotiated, ECN mark observed, and potential real CE mark observer~~
- ~~ECN negotiated and ECN mark observed (SEW->SAE + ECT[0,1])~~
- ~~ECN negotiated but no ECN mark observed (SEW->SAE)~~
- ~~ECN not negotiated (SEW -> SA)~~
- ~~ECN connection failed (SEW -> X, while S -> SA)~~
- ~~Target Down (SEW -> X, S -> X)~~

Actually, let's do it this way: an observation can have multiple conditions. The following potential conditions are exclusive.

- Target Down (no connections work) vs ECN-dependent connectivity (ECN fails) vs ECN-independent connectivity (connection state same) vs possibly-transient connectivity (non-ECN fails)
- ECN negotiated vs ECN not negotiated
- ECT0 mark seen post-negotiation vs ECT0 mark seen pre-negotiation vs ECT0 mark not seen
- ECT1 mark seen post-negotiation vs ECT0 mark seen pre-negotiation vs ECT1 mark not seen
- CE mark seen post-negotiation vs CE mark seen pre-negotiation vs CE mark not seen

**Comment by britram** [comment]
In more detail, the fields of the JSON document should be as follows:

```
{
  time:
  sip:
  dip:
  hostname: (www.xxx.yyy, if relevant)
  rank: (from the alexa list, if relevant)
  condition: (some encoding of the list in the previous comment)
  observations: [
    {
      ecnstate: True,
      sp:, dp:, ect0,: ect1:, ce:, other flags...
    },
    {
      ecnstate: True,
      sp:, dp:, ect0,: ect1:, ce:, other flags...
    },
  ]
}
```

**Comment by britram** [comment]
This should happen after the `standalone-observer`, `multiprocessing-observer`, and `mpo-all-results` branches merge back to master.

**Comment by gubser** [comment]
also look at mami-project/pto-core#16
