### ISSUE TITLE
Result reporting doesn't work for IPv6

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#33]
There's something wrong with IPv6 result merging:

```
DEBUG:pathspider:got a result (2a00:bdc0:3:103:1:0:403:805, 0)
DEBUG:pathspider:got a result (2a00:bdc0:3:103:1:0:403:805, 0)
DEBUG:pathspider:won't merge duplicate result
```

The second `0` in the debug output here is supposed to be the source port number. It's not clear what's breaking this.

**Comment by irl** [comment]
The packets never existed.
