### ISSUE TITLE
Add an option to store a pcap trace of all packets seen by the Observer

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#39]
Someone from the OONI community has asked if it would be possible to also store a PCAP trace of all the packets that were seen during a measurement run, for debugging or for deeper analysis of the data that the original observer functions may not have recorded enough detail for.

I don't think that this would be too difficult to add as an option.

**Comment by irl** [comment]
This is now also a requirement for a MONROE project.

**Comment by britram** [comment]
We can do this with a pylibtrace-based Observer, but it will be slow, since all the bytes of every packet will have to take a roundtrip through a Python bytearray.
