### ISSUE TITLE
add SCTP and SCTP/UDP connectivity testing

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#4]
We need to work out what it is that we want to look at here.

Some options:
- Do SCTP services also support SCTP/UDP?
  - I'm not sure this is entirely likely
- From multiple vantage points, can we successfully make connections to SCTP services?
  - This is the SCTP vs ICMP test we discussed in the kickoff meeting

NEAT may be able to inform this better.

**Comment by irl** [comment]
Waiting for twisted.plugin to be implemented before starting this, but should be relatively simple. Will also need a tool based on massscan probably to scrape some SCTP endpoints to use.

**Comment by irl** [comment]
Blocked by #17

**Comment by irl** [comment]
@adventureloop Do you have thoughts on this?

**Comment by irl** [comment]
This is no longer a bug on PATHspider, this should be implemented as a separate plugin.
