### ISSUE TITLE
Add timeout for TFO connection in tfospider

### ISSUE THREAD

**Issue by agermann93** [mami-project/pathspider#41]
The TFO connection setup in connect() of tfospider is not on a time out. Since socket.settimeout() does not work on socket.sendto(). This can cause connect() to get stuck on non-responsive hosts.

**Comment by irl** [comment]
@britram Is this still an issue?

**Comment by britram** [comment]
Yes, but we've worked around it by creating DesynchronizedSpider. The issues is with the underlying API, so a fix is hard. I'd still like to figure out whether there's something we can do without redesigning away from multithreading and using SIGALRM (yay).

**Comment by britram** [comment]
DesynchronizedSpider and making the TFO attempt conditional on non-TFO connection seem to have fixed this one well enough to make the TFO plugin usable at scale. I think this is as good as we can do from Python.
