### ISSUE TITLE
Easy way to get TCP option from packet

### ISSUE THREAD

**Issue by agermann93** [mami-project/pathspider#42]
TFOSpider checks packets for TFO option by parsing the TCP header. This is slow and causes problems with multiple workers (>5), leading to not observed flows.

**Comment by britram** [comment]
Unfortunately, there are no functions in libtrace for handling TCP options. There are two possible ways to handle this:

1. Parse the TCP options in Python, like TFOSpider does now.
2. Fork python-libtrace and add a TCP options parser written in C there.

I'll talk to Nevil this week.

**Comment by britram** [comment]
Replaced by #56
