### ISSUE TITLE
Add ECMP awareness

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#43]
Pathspider was designed to run two connections as close to simultaneously as possible, to reduce transience. This means that the connections in each state use different source ports, which also helps to match flows from the observers with results by source port and destination address.

This is obviously bad for trying to isolate paths in an ECMP environment. 

We should investigate (1) timestamp-based matching in the merger and (2) serial as opposed to parallel testing, to make it possible to run two tests using the same flow label.

**Comment by irl** [comment]
I was considering a hook for a {paris-,dublin-,}traceroute. It adds considerable overhead in packets sent but I'm not sure it adds much timewise as we're often waiting for replies and timeouts anyway.

**Comment by britram** [comment]
These are two separate issues:

(1) You need to run multiple probes in order to scan flow ID space; and

(2a) You need to be able to run the A test and the B test using exactly the same flow ID, or

(2b) you need to use traceroute on every flow ID you used during the flow ID space scan to match A tests to B tests.

The problem I raised in filing this issue is issue 2a: (I) since we use source ports to match observed flows to result records, and (II) since the whole point of pathspider's byzantine synchronization stuff is opening two connections as simultaneously as possible, we cannot do this without a fairly basic rethinking of the design.

Running traceroute with the same flow IDs could at least add a note to an observation that the paths are incongruent, but this is a thing that should happen in the repository. Adding flow ID information to the observation would at least allow the observatory to link Paris traceroute results to PathSpider results and enrich the path information.

Pinging @gubser so he can think about this too. :)

**Comment by britram** [comment]
Nothing you can do about this in PATHspider. Detecting ECMP is a post-measurement analysis problem.
