### ISSUE TITLE
Provide a means to disable the semaphores

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#46]
Where a plugin does not require locking for global state, it should be possible to speed up the semaphores somehow.

Some options:

 * These plugins should just use the ``post_connect()`` function instead of ``connect()`` so that all that is locked is just ``pass``.
 * Removing the semaphore acquisition function calls with a conditional (not sure what this would break).

This would be relevant for the TFO plugin.

**Comment by britram** [comment]
We've wanted to generalize two configurations to n configurations for a while now. I think the best way to do this is fix it in docs: "use post_connect() if you don't need system configuration". Maybe "connect()" and "post_connect()" should be renamed...?

**Comment by britram** [comment]
Actually, since timeouts seem to be taking a *very* long time in TFOSpider, I'm working on removing synchronization on configurations completely in the `desync` branch.

**Comment by britram** [comment]
Done, `desync` merged.
