### ISSUE TITLE
Write integration tests for Observer

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#47]
libtrace can accept a pcap trace as its input, and so integration testing of the Observer class can be performed without having a PATHspider plugin to generate traffic.

For each plugin, an example input (possibly with crafted packets to allow for edge cases to be tested) and example output should be provided.

**Comment by irl** [comment]
Integration testing will have to happen in a later release, but we're starting to write unit tests.

**Comment by irl** [comment]
We have now "it can run over the packets and check the correct number of flows exist". We still need plugin specific tests for the chain functions.

**Comment by irl** [comment]
Need testing for each of the plugins:

* [x] ECN
* [ ] DSCP
* [ ] TFO
* [ ] TLS (waiting for #66)

**Comment by irl** [comment]
Once DSCP and TFO are covered, this is done for 1.0.0 and can be reassigned to 1.1.0.

@britram Can you provide a test trace for TFO?

**Comment by britram** [comment]
test trace committed

**Comment by irl** [comment]
These are basically all here now, closing this issue. We can open new issues for individual plugins if needed in the future.
