### ISSUE TITLE
Add a pathspider.helpers.tor with connect_tor and connect_http_tor

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#48]
The Tor network provides a large number of exits that can be used to probe the core for transparency issues.

Tor exits often receive special treatment, and so this should be accounted for in the analysis of any test results.

[meejah/txtorcon](https://github.com/meejah/txtorcon) could be used for this and this is already packaged in Debian (by @irl).

One test that could use this is the H2 test in #44.

**Comment by irl** [comment]
This should be done in a similar manner to the MONROE wrapper. The MONROE wrapper can be generalised as it's using Netlink messages for detecting invalidation of results due to link failure, not the proprietary MONROE metadata service. We can build both of these in as seperate entry points, or as command line switches calling wrapper functions.

**Comment by meejah** [comment]
"very soon", there will be some much nicer interfaces for doing streams-over-a-circuit in txtorcon, so you can get back an `IStreamClientEndpoint` that will go via a particular circuit on `.connect()` -- which probably helps for use-cases like this (see the `release-1.x` branch in txtorcon if you're interested).

**Comment by irl** [comment]
Thanks @meejah (: That sounds awesome!

**Comment by britram** [comment]
Implement this as a helper (like #70, #74). Plugins will need to be aware of the fact they're using Tor, but this makes sense.

**Comment by meejah** [comment]
p.s. the API I spoke of above is in master now as `Circuit.stream_via`.
