### ISSUE TITLE
PATHspider does not exit when running with example csv

### ISSUE THREAD

**Issue by gubser** [mami-project/pathspider#50]
```
vagrant@contrib-jessie:/data/pathspider$ sudo pathspider -I examples/webtest.csv -o /home/vagrant/out.fjson
...
DEBUG:pathspider:all workers joined
```
and then it doesn't exit (waited more than 5min)

it does not affect 0.9.0 so far.

**Comment by irl** [comment]
@gubser Please try with latest master; works for me, cannot reproduce. Tested with master in vagrant and on my laptop with:

    sudo /usr/bin/env PYTHONPATH=. python3 pathspider/run.py -I examples/webtest.csv -i enp0s25 -o /tmp/output.txt

Re-open if this is still an issue.
