### ISSUE TITLE
Replace QoF with a libtrace-based flexible flowmeter in pure Python

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#6]
Build a flowmeter that allows packet inspection in Python to annotate records that can be merged with Pathspider traffic generator information. Allow dynamic addition of packet inspection functions and flow properties.

This is in progress in the observer branch. It'll be way slower than QoF, but given our requirements most probably fast enough.

**Comment by britram** [comment]
Observer seems to work. Next step: create ObSpider, which will replace QofSpider with an observer-based flow queue.

**Comment by britram** [comment]
Will need the ability to run observer with sufficient permissions for live capture. For many platforms this is probably a fix-in-documentation thing ("set the user to have sufficient permissions to do live capture"), but it means we might need a way to separate the observer into its own process. Probably doable, since the observer will basically only communicate with the rest of the system via a queue.

**Comment by britram** [comment]
In ObSpider, start the observer using multiprocessing, then drop privileges using [`os.seteuid(int(os.envion['SUDO_USER']`](http://stackoverflow.com/questions/15705439/python-drop-root-privileges-for-certain-operations)

**Comment by irl** [comment]
We can use filesystem permissions to achieve this without having to run it as sudo, i.e. just giving it capture permissions.

An example where I've done this before: http://sources.debian.net/src/xastir/2.0.6-4/debian/xastir.postinst/
