### ISSUE TITLE
Generalize pathspider to allow for A/B testing without sysctl

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#7]
Pathspider evolved from ECNSpider, which tested kernel code switched on and off by an sysctl, leading to a tight synchronization between testing and configurator threads. Some A/B tests (e.g. injected packets with Scapy) don't need to do this. Generalize Pathspider to make the configurator optional, and used only when it's needed.

There are a few possible design patterns to use here, which we should discuss.

**Comment by irl** [comment]
Hopefully remembering everything we discussed in Zurich -

- [ ] The configurator is not optional, but when overwritten by subclasses can just be "pass"
- [ ] The configurator should be able to:
 - [ ] Perform sysctl changes
 - [ ] Perform remote sysctl changes (not necessarily required by MAMI but easy to implement)
 - [ ] Perform routing table changes (for initial window)
 - [ ] Set variables that can affect the worker

**Comment by irl** [comment]
This is mostly done, but I will close this issue when I add in support for twisted.plugin and have things like ecnspider and tfospider being loaded dynamically by the standalone harness (and the mPlane harness can then do the same).

**Comment by irl** [comment]
Done
