### ISSUE TITLE
Move tcp_connect and dns_query to helpers.py

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#70]
These are both only useful for SynchronisedSpider and this seperates it from the base spider while not creating extra complexity. #71 has been merged into this issue.

**Comment by irl** [comment]
tcp_connect is in SynchronizedSpider, not going to have DNS in 1.0.x

**Comment by pietdevaere** [comment]
There is now a separate file for this functions, and they should be moved there.

**Comment by britram** [comment]
See #112
