### ISSUE TITLE
explore architectures for faster Observers

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#72]
Pathspider moved from QoF to the Observer in order to make enhancements/plugins easier to write -- traffic generation and traffic observation could be done in the same language (without QoF's technical debt to YAF). This traded speed we didn't need as much of for convenience we did, and was on balance a pretty good tradeoff.

Additional requirements on the Observer -- options parsing for TFO (#56); packet trace storage (#39) -- make it slower. Eventually they make it too slow to be useful. It may make sense to keep the multiprocessing-like split between Observer and not, but to implement the observer separately in a faster language (e.g. Cython, or something entirely separate but modern like Go.)

**Comment by irl** [comment]
I think it wouldn't be terrible to have the observer done in C with Python bindings. This would be my preferred route for speed.

**Comment by britram** [comment]
Consider https://github.com/britram/mokumokuren as a basis for this as well.
