### ISSUE TITLE
job_feeder should check input has valid port number, emit warning and skip if not

### ISSUE THREAD

**Issue by pietdevaere** [mami-project/pathspider#76]
e.g. when the input file is in the wrong format, `job_feeder()` can crash on ` row[1] = int(row[1])`.
When this happens, pathspider will not exit, but will be stuck in an infinite loop.

**Comment by irl** [comment]
This is a common thing that's been happening, but we're catching most of the cases now. If this is fixed, a test should be added to avoid regression.
