### ISSUE TITLE
ECN_post_connect() should download webpage

### ISSUE THREAD

**Issue by pietdevaere** [mami-project/pathspider#89]
otherwise no ECT codepoints can be seen

**Comment by pietdevaere** [comment]
Actually, I think that this should be done by connect(), as if we run it in post_connect() we might be sending ECN / non ECN enabled packages over a connection without / with ECN negotiated.

**Comment by britram** [comment]
No.

This is the whole point of the convoluted synchronization in Pathspider: connect() runs in each config (to get a socket in that config), post_connect does anything that might take longer (to keep from blocking other connect() calls, and so the config 0 socket and config 1 socket are created as close in time to each other as practicable.

**Comment by pietdevaere** [comment]
Ok, so if we have created a socket with ECN disable, and then we enable ECN, will packets send over that socket be ECN-enabled?

**Comment by britram** [comment]
Yep. The enable switch just enables negotation. Negotiation state is stored in the skb.

**Comment by pietdevaere** [comment]
implemented in c0b8c0afd7f708d701c13bfc1e08e26cde4509a4 through 27366ba42805328e0fee0f8ad2d5f83839e1649c. In latest version only HEAD request is performed, but this can be changed easily
