### ISSUE TITLE
Provide output in mPlane format

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#9]
This will allow the pathspider client to be used as a component itself (though we don't necessarily need to do the full wrapper yet)

**Comment by irl** [comment]
@britram We really need to document output formats before we can release. Do we still want to go for mPlane format for 1.0.0 or is "native observer format" a better target?

**Comment by britram** [comment]
I think we'd like to document the existing CSV input and FJSON outputs. We probably want to add FJSON input as well. Once we have that, we can mutate FJSON to mPlane-compliant FJSON.
