### ISSUE TITLE
http_get() helper function needed

### ISSUE THREAD

**Issue by pietdevaere** [mami-project/pathspider#90]
when passed a socket, it should perform a HTTP request and return the response.

**Comment by irl** [comment]
This should be implemented as a helper function either on SynchronisedSpider or perhaps we move these into a new package. #70 and #74 are perhaps relevant.

**Comment by pietdevaere** [comment]
Why should this be implemented on `SynchronisedSpider`? Doen't it make more sense to make it a static function of `Spider`?

**Comment by irl** [comment]
tcp_connect and dns_query were planend to be on SynchronisedSpider for the reason that these are not very useful for a DesyncSpider. If you're always doing the same function, there should have been some global state change and that only happens on the SyncSpider.

Now that these are growing though, perhaps moving these to a seperate module is a good idea.

**Comment by pietdevaere** [comment]
fixed in c0b8c0afd7f708d701c13bfc1e08e26cde4509a4 through 27366ba42805328e0fee0f8ad2d5f83839e1649c
