### ISSUE TITLE
differentiate between ECT and CE codepoints in SYN/ACK or regular packet

### ISSUE THREAD

**Issue by pietdevaere** [mami-project/pathspider#91]

**Comment by britram** [comment]
@irl did you do this?

**Comment by britram** [comment]
This goes in chains.py #113

**Comment by irl** [comment]
@britram Should there be new conditions for this or just adding this to the flow records?

**Comment by irl** [comment]
@britram Reopen this issue if you want to have new conditions, currently the data will be in the flow record but not used for condition generation.
