### ISSUE TITLE
HTTP requests should be made faster / in parallel 

### ISSUE THREAD

**Issue by pietdevaere** [mami-project/pathspider#94]
Some HTTP servers will close a connection after a few seconds when no request is made.
Because the ECN and non-ECN requests are currently executed in series, it is possible that the server has already closed the connection before an attempt to perform a non-ECN HTTP request was made.

**Comment by pietdevaere** [comment]
Fixed this by performing sending the request in `connect`, and receiving the response in `post_connect`. Currently the solution is bodged, and is in a separate branch.

In order to properly implement this, #95 should be implemented first

**Comment by britram** [comment]
@pietdevaere the partial solution is in bodges-piet?

**Comment by pietdevaere** [comment]
affirmative
