### ISSUE TITLE
spiderrecord fields renamed

### ISSUE THREAD

**Issue by pietdevaere** [mami-project/pathspider#97]
In order to fix #96, I had to include the source ip from the connection socket to the connection results.

In order to prevent totally absurd and illogical naming, that meant that I had to rename some of the fields of SpiderRecord. Unfortunately, this also means that _all_ plugins need to be updated. As I did not do so, tfo and tls are no br0ken. Therefore, I have branched of master, and am currently developing in `spiderreocord_rename` until tfo and tls are updated.

**Comment by pietdevaere** [comment]
this is now in `bodges piet`

**Comment by britram** [comment]
will be fixed as part of remerge #110
