### ISSUE TITLE
Public IP should be added to flow

### ISSUE THREAD

**Issue by pietdevaere** [mami-project/pathspider#99]
when running behind a NAT, the public IP should be added to the flow info.

**Comment by britram** [comment]
Consider using RIPE Atlas Anchors for discovering public IP information.

**Comment by irl** [comment]
I think we can use http://checkip.dyndns.org/

RIPE Atlas Anchors are not accessible afaict, only to RIPE Atlas probes. This will require that #112 and #73 are completed so that we have a means of connecting through the correct interface when checking.
